"""Add notification jobs

Revision ID: 35019c58cec6
Revises: f0ad8769bb8a
Create Date: 2026-09-16 00:53:46.411131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35019c58cec6'
down_revision: Union[str, Sequence[str], None] = 'f0ad8769bb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_jobs_next_attempt_at'), 'notification_jobs', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notification_jobs_status'), 'notification_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_notification_jobs_submission_id'), 'notification_jobs', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_jobs_submission_id'), table_name='notification_jobs')
    op.drop_index(op.f('ix_notification_jobs_status'), table_name='notification_jobs')
    op.drop_index(op.f('ix_notification_jobs_next_attempt_at'), table_name='notification_jobs')
    op.drop_table('notification_jobs')
    # ### end Alembic commands ###
