"""Make user email globally unique

Revision ID: 921fad674f61
Revises: 6691a8136f81
Create Date: 2026-09-14 18:07:19.877694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921fad674f61'
down_revision: Union[str, Sequence[str], None] = '6691a8136f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_tenant_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_tenant_email'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
